[package]
name = "cpf_cnpj_validator"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
regex = "1.5"
tokio = { version = "1.0", features = ["full"] }
md-5 = "0.10.6"
sha-1 = "0.10.1"
sha2 = "0.10.8"
