version: '3.8'

services:
  dev:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    command: sh -c "cargo install watch && cargo watch -x run"
    environment:
      - RUST_LOG=info

  prod:
    build:
      context: .
      target: builder
    ports:
      - "3030:3030"
    restart: unless-stopped